### ISSUE TITLE
Can not work for ava dataset?

### ISSUE THREAD

**Issue by xushichao2016** [tefantasy/CorrNet#1]
Thank you for your great work!

could you share the ava_dataset.py ?
![image](https://user-images.githubusercontent.com/32624985/103168348-5cc54780-486d-11eb-9eb7-3329ccd1e7cb.png)

**Comment by xushichao2016** [comment]
Thank you for your great work!

could you share the ava_dataset.py ?


![image](https://user-images.githubusercontent.com/32624985/103168212-3226bf00-486c-11eb-8755-0932a963b0b7.png)

**Comment by tefantasy** [comment]
Sorry, there's no support for ava dataset (action detection) here. Our implementation only supports classification.

**Comment by xushichao2016** [comment]
But, when we do classification test on AVA dataset, the following error occurs，  

File "/home/xwy/.conda/envs/slowfast/lib/python3.6/site-packages/torch/utils/data/_utils/collate.py", line 55, in default_collate
    return torch.stack(batch, 0, out=out)
RuntimeError: stack expects each tensor to be equal size, but got [1, 80] at entry 0 and [2, 80] at entry 2


![image](https://user-images.githubusercontent.com/32624985/103189679-c6defa80-4908-11eb-870d-131080d7b0a1.png)

**Comment by tefantasy** [comment]
I am sorry that I have no experience with AVA dataset. 

One thing that might cause a problem is here
https://github.com/tefantasy/CorrNet/blob/106f7cc350c5b3edffb265fb6fe5d51745a0dc84/corr_net/models/correlation_net/corr_net.py#L103
, where we expect a list that contains one tensor is fed as the input of the forward method. This follows the interface in [PySlowFast](https://github.com/facebookresearch/SlowFast), in which some models require more than one tensor as input (thus a list of tensors). If you wrote a data-loading script for AVA dataset, please be aware of this (remove this line of code if you directly feed a tensor to the input of the forward method). 

If this is the case that cause your problem, please let me know in this issue.
